name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm install
    - run: npm run build --if-present
    - name: Run frontend tests
      run: |
        cd frontend
        npm install
        node ../testcase.js
    - name: Run other tests
      run: npm test
