name: React Test CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        npm install --save-dev @testing-library/react @testing-library/jest-dom react-scripts
    - name: Verify package installations
      run: |
        cd frontend
        npm ls @testing-library/react @testing-library/jest-dom react-scripts
    - name: Create Jest config
      run: |
        cd frontend
        echo "module.exports = {
          testEnvironment: 'jsdom',
          setupFilesAfterEnv: ['@testing-library/jest-dom'],
        };" > jest.config.js
    - name: Verify Simple React test file
      run: |
        cd frontend
        cat SimpleComponent.test.js
    - name: Run Jest directly
      run: |
        cd frontend
        npx jest --no-cache --config=jest.config.js SimpleComponent.test.js
    - name: Run tests with React Scripts
      run: |
        cd frontend
        CI=true npm test -- --testMatch='**/SimpleComponent.test.js'
