name: React Test CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        npm install --save-dev jest @testing-library/react @testing-library/jest-dom jest-environment-jsdom @babel/preset-env @babel/preset-react babel-jest
    - name: Verify package installation
      run: |
        cd frontend
        npm list jest jest-environment-jsdom @testing-library/react @testing-library/jest-dom
    - name: Create Jest config
      run: |
        cd frontend
        echo "module.exports = {
          testEnvironment: 'jsdom',
          transform: {
            '^.+\\.jsx?$': 'babel-jest',
          },
          setupFilesAfterEnv: ['./setupTests.js'],
          moduleDirectories: ['node_modules', 'src'],
          testMatch: ['**/testcase.js'],
        };" > jest.config.js
    - name: Create setup file for Jest
      run: |
        cd frontend
        echo "import '@testing-library/jest-dom';" > setupTests.js
    - name: Create Babel config
      run: |
        cd frontend
        echo '{
          "presets": ["@babel/preset-env", "@babel/preset-react"]
        }' > .babelrc
    - name: Copy testcase.js to frontend directory
      run: cp testcase.js frontend/
    - name: Check frontend directory contents
      run: |
        cd frontend
        ls -la
    - name: Check testcase.js content
      run: |
        cd frontend
        cat testcase.js
    - name: Run tests
      run: |
        cd frontend
        npx jest --config jest.config.js --verbose
