name: React Test CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        npm install --save-dev jest @babel/preset-env @babel/preset-react @testing-library/react @testing-library/jest-dom
    - name: List frontend directory contents
      run: |
        cd frontend
        ls -la
    - name: Display testcase.js content (if it exists)
      run: |
        cd frontend
        if [ -f testcase.js ]; then
          cat testcase.js
        else
          echo "testcase.js not found in frontend directory"
        fi
    - name: Create Jest config
      run: |
        cd frontend
        echo "module.exports = {
          testEnvironment: 'jsdom',
          setupFilesAfterEnv: ['@testing-library/jest-dom'],
          transform: {
            '^.+\\\\.(js|jsx)$': 'babel-jest'
          },
          testMatch: ['**/testcase.js']
        };" > jest.config.js
    - name: Run tests from testcase.js
      run: |
        cd frontend
        npx jest --config=jest.config.js
