name: React Test CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        npm install --save-dev jest @testing-library/react @testing-library/jest-dom jest-environment-jsdom @babel/preset-env @babel/preset-react babel-jest
    - name: Create Jest config
      run: |
        cd frontend
        echo "module.exports = {
          testEnvironment: 'jsdom',
          transform: {
            '^.+\\.jsx?$': 'babel-jest',
          },
          setupFilesAfterEnv: ['@testing-library/jest-dom/extend-expect'],
          moduleDirectories: ['node_modules', 'src'],
        };" > jest.config.js
    - name: Create Babel config
      run: |
        cd frontend
        echo '{
          "presets": ["@babel/preset-env", "@babel/preset-react"]
        }' > .babelrc
    - name: Move testcase.js to frontend
      run: mv testcase.js frontend/
    - name: Run tests
      run: |
        cd frontend
        npx jest testcase.js
