name: React Test CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Setup and Run Tests
      run: |
        # Navigate to frontend directory
        cd frontend

        # Install dependencies
        npm install
        npm install --save-dev jest @testing-library/react @testing-library/jest-dom jest-environment-jsdom @babel/core @babel/preset-env @babel/preset-react babel-jest react react-dom

        # Create Babel config
        echo '{
          "presets": ["@babel/preset-env", "@babel/preset-react"]
        }' > .babelrc

        # Create Jest config
        echo '{
          "testEnvironment": "jsdom",
          "transform": {
            "^.+\\.jsx?$": "babel-jest"
          },
          "setupFilesAfterEnv": ["<rootDir>/setupTests.js"],
          "moduleDirectories": ["node_modules", "src"]
        }' > jest.config.json

        # Create setup file for Jest
        echo "import '@testing-library/jest-dom';" > setupTests.js

        # Copy testcase.js from root to frontend directory
        cp ../testcase.js .

        # Run the tests
        npx jest --config=jest.config.json testcase.js
